#!/usr/bin/env bash
# Generate frontend/public/env-config.js from deploy/.env
set -e

cd "$(dirname "$0")/.."

if [ -f deploy/.env ]; then
    set -a
    source deploy/.env
    set +a
fi

APP_PROTOCOL="${APP_PROTOCOL:-https}"
APP_DOMAIN="${APP_DOMAIN:-draw.local}"
GIPHY_API_KEY="${GIPHY_API_KEY:-}"

cat > frontend/public/env-config.js << EOF
// Runtime environment configuration - generated by 'just dev'
window.__ENV__ = {
  VITE_APP_WS_SERVER_URL: "${APP_PROTOCOL}://${APP_DOMAIN}",
  VITE_APP_BACKEND_V2_GET_URL: "${APP_PROTOCOL}://${APP_DOMAIN}/api/v2/scenes/",
  VITE_APP_BACKEND_V2_POST_URL: "${APP_PROTOCOL}://${APP_DOMAIN}/api/v2/scenes/",
  VITE_APP_STORAGE_BACKEND: "http",
  VITE_APP_HTTP_STORAGE_BACKEND_URL: "${APP_PROTOCOL}://${APP_DOMAIN}/api/v2",
  VITE_APP_FIREBASE_CONFIG: "",
  VITE_APP_DISABLE_TRACKING: "true",
  VITE_APP_GIPHY_API_KEY: "${GIPHY_API_KEY}"
};
EOF

echo "Created frontend/public/env-config.js"

